=== AatifaKhan0112/webtech/exam_ques5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="rollno" type="xs:integer"/>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="email" type="xs:string"/>
                            <xs:element name="department">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="CSE"/>
                                        <xs:enumeration value="ECE"/>
                                        <xs:enumeration value="ME"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== AatifaKhan0112/webtech/exam_ques5.xml
<?xml version="1.0" encoding="UTF-8"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="exam_ques5.xsd">
    <student>
        <rollno>101</rollno>
        <name>Aatifa Khan</name>
        <email>aatifa@example.com</email>
        <department>CSE</department>
    </student>
    
    <student>
        <rollno>102</rollno>
        <name>Rahul Verma</name>
        <email>rahul@example.com</email>
        <department>ECE</department>
    </student>
    
    <student>
        <rollno>103</rollno>
        <name>Sneha Singh</name>
        <email>sneha@example.com</email>
        <department>ME</department>
    </student>
</students>
